---
- name: Install MySQL in a non-interactive manner
  shell: 'echo "{{item}}" | sudo debconf-set-selections'
  with_items:
    - 'mysql-server mysql-server/root_password password root'
    - 'mysql-server mysql-server/root_password_again password root'

- name: Install MySQL Server
  apt: pkg=mysql-server update_cache=yes
  sudo: yes

- name: Bind MySQL to 0.0.0.0
  lineinfile: 'dest=/etc/mysql/my.cnf regexp=^bind\-address line="bind-address = 0.0.0.0"'
  sudo: yes

- name: Restart MySQL
  service: name=mysql state=restarted
  sudo: yes
