---
  - name: Install the Docker PGP key
    shell: "sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && touch .docker_pgp_key"
    args:
      creates: ".docker_pgp_key"

  - name: Install HTTPS support in Apt
    apt: pkg="{{item}}"
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add the Docker Apt repository
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

  - name: Install Docker Engine
    apt: pkg=docker-engine update_cache=yes
    notify:
      - Start Docker
