---
- hosts: '{{target}}'
  remote_user: vagrant
  sudo: yes

  roles:
    - { role: java-oracle, major_version: 8, minor_version: 40, build_number: 25}
    - { role: stash, version: 3.7.0, tags: [ 'dev-mode' ] }

  tasks:
    - name: Ensure Git is installed
      apt: pkg=git
      
    - name: Ensure Perl is installed
      apt: pkg=perl
