---
- name: Download the jenkins-ci.org PGP key
  get_url: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key dest=~/jenkins-ci.org.key
  sudo: yes

- name: Add the jenkins-ci.org PGP key
  apt_key: file=~/jenkins-ci.org.key
  sudo: yes

- name: Add the jenkins apt repository
  apt_repository: 'repo="deb http://pkg.jenkins-ci.org/debian binary/" update_cache=yes'
  sudo: yes

- name: Create 'jenkins' group
  group: name=jenkins
  sudo: yes

- name: Create 'jenkins' user
  user: name=jenkins group=jenkins groups=vagrant append=yes
  sudo: yes

- name: Ensure JENKINS_HOME exists
  file: path=/var/data/jenkins state=directory owner=jenkins group=jenkins
  sudo: yes

- name: Set JENKINS_HOME
  lineinfile: 'dest="/etc/environment" regexp="^JENKINS_HOME=" line="JENKINS_HOME=/var/data/jenkins"'
  sudo: yes

- name: Install jenkins
  apt: pkg=jenkins
  sudo: yes
