---
- include: rvm.yml

- name: Install Rails (MRI)
  script: "install-rails.sh.lf {{ruby_version}}"
  when: ruby_interpreter == 'mri'

- name: Install Rails (JRuby)
  script: "install-rails-jruby.sh.lf"
  when: ruby_interpreter == 'jruby'
