---
- name: Ensure the global cache directory exists
  file: path=/var/cache/hivemind state=directory

- name: Ensure GnuPG is installed
  apt: 'pkg={{item}}'
  with_items:
    - gnupg
    - curl
    - nodejs
  sudo: yes

- name: Download Michal Papis' GPG key
  get_url: url=https://rvm.io/mpapis.asc dest=/var/cache/hivemind/mpapis.asc validate_certs=no

- name: Import Michal Papis' GPG key
  shell: 'gpg --import /var/cache/hivemind/mpapis.asc'

- name: Download the RVM install script
  get_url: url=https://get.rvm.io dest=/var/cache/hivemind/rvm_installer.sh validate_certs=no

- name: Install RVM
  shell: 'cat /var/cache/hivemind/rvm_installer.sh | bash -s stable'

- name: Add RVM to ~/.bashrc
  shell: 'echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc'
