---
- name: Create the 'tomcat' group
  group: name=tomcat
  sudo: yes

- name: Create the 'tomcat' user
  user: name=tomcat group=tomcat groups=vagrant append=yes
  sudo: yes

- name: Download the Tomcat archive
  get_url: url="{{tomcat_download_url}}" dest="/var/cache/hivemind/{{tomcat_package_filename}}"
  sudo: yes

- name: Extract the Tomcat archive
  shell: "mkdir {{tomcat_install_dir}} && tar zxf /var/cache/hivemind/{{tomcat_package_filename}} --directory={{tomcat_install_dir}} --strip-components=1 creates={{tomcat_install_dir}}"
  sudo: yes

- name: Copy the default Tomcat users file
  copy: src=default-tomcat-users.xml dest="{{tomcat_install_dir}}/conf/tomcat-users.xml"
  sudo: yes

- name: Grant ownership of Tomcat installation to 'tomcat' user
  file: path="{{tomcat_install_dir}}" owner=tomcat group=tomcat recurse=yes
  sudo: yes

- name: Copy the Tomcat init script
  template: src=tomcat.j2 dest=/etc/init.d/tomcat mode=0755
  sudo: yes

- name: Set CATALINA_OPTS
  lineinfile: dest=/etc/environment regexp=^CATALINA_OPTS= line=CATALINA_OPTS="{{jvm_xmx}}"
  sudo: yes

- name: Turn Tomcat into a system service
  service: name=tomcat enabled=yes
  sudo: yes
